version: "3.5"

services:
  frontend:
    image: iazuri/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    networks:
      - app-network

  backend:
    image: iazuri/backend:latest
    container_name: backend
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

volumes:
  database:

networks:
  app-network:
