name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend

      
      - name: Build frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend

      
      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
