name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest ./frontend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          script: |
            cd /path/to/project
            docker compose pull
            docker compose up -d --remove-orphans
